#!/bin/bash
I study software engineering at alx,i am form Nigeria an i live at oeoriya number 5 oyebola street.My ambition is t become a sofware engineer and make this contyr a better place with good tech 
